#!/system/bin/sh

# Activate swap
if [ "$(cat /proc/partitions | grep mmcblk0p3)" != "" ]; then
	swapon /dev/block/mmcblk0p3
fi

# Activate compcache (using new sysctl method; not supported officially by CyanogenMod?)
if getprop | grep persist.service.compcache; then
	COMPCACHE=`getprop persist.service.compcache`
else
	COMPCACHE=`getprop ro.compcache.default`
fi

if [ "$COMPCACHE" -ne "0" ]; then
	COMPCACHERAM=$((184 * $COMPCACHE / 100))
	insmod /system/lib/modules/zram.ko
	echo 1 > /sys/block/zram0/reset
	echo $(($COMPCACHERAM*1024*1024)) > /sys/block/zram0/disksize
	mkswap /dev/block/zram0
	swapon /dev/block/zram0
fi

#patch simple2ext's script to prevent filesystem corruption
S2ECONFIG="/data/local/s2e_config/.mounts_ext4"
if [ -f $S2ECONFIG ];
then
	# remove dangerous tune2fs tweaks
	sed -i -e 's/ tune2fs -/ #tune2fs -/g' -e 's/ e2fsck/ #e2fsck/g' \
	-e 's/-o commit=19,barrier=0,nobh,nouser_xattr,errors=continue,noatime,nodiratime,nosuid,nodev,data=writeback//g' $S2ECONFIG
fi

echo "try link huawei additional partition"
if [ -b /dev/block/mtdblock7 ];
then
	mkdir /data/cust;
	chown 1000.1000 /data/cust;
	chmod 777 /data/cust;
	mount /dev/block/mtdblock7 /data/cust;
fi 

# sdcard speed fix

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ];
then
    /system/xbin/echo "4096" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
fi

#real IO improve from v9.0 !!!!!

echo "bfq" > /sys/block/mmcblk0/queue/scheduler;
echo 1 > /sys/block/mmcblk0/queue/rotational;
for i in 1 2 3 4 5;
do
	echo "bfq" > /sys/block/mtdblock$i/queue/scheduler;
	echo 0 > /sys/block/mtdblock$i/queue/rotational;
done

